<?php
/**
 * Created by PhpStorm.
 * User: 百鬼夜行
 * Date: 2017/8/23
 * Time: 15:38
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Baby extends Model
{
   //指定表名
    protected $table = 'baby';
    //指定id
    protected $primaryKey = 'id';
    //自动维护时间戳  默认true
    public $timestamps = true;
    //指定允许批量赋值的字段
    protected $fillable = ['name','age'];
    //指定不允许批量复制的字段
    protected $guarded = [''];


    //时间戳 默认填入形式
    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }


    public function show(){
        return 'show-baby';
    }
    public static function show2(){
        return 'hoho';
    }
}